### ISSUE TITLE
Missing chapters and wrong order Manhwa18.com

### ISSUE THREAD

**Issue by sjiawjbssj** [keiyoushi/extensions-source#2281]
### Source information

Manhwa18 1.4.11

### Source language

English

### Steps to reproduce

Open e.g. "Secret class" scroll down to chapter 67.

### Expected behavior

Chapters should be in the correct order and no missing chapter warning should be shown.

### Actual behavior

Chapters 66 and 67 are in the wrong order and a missing chapter warning is shown.

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
It's how the source listed it themselves (go look for yourself in WebView or your own browser), nothing we can do about it on our end. 

But you can set that title to sort by chapter number (instead of by source) to get it in the right order in the app.

**Comment by sjiawjbssj** [comment]
I didn't notice, thanks.
