### ISSUE TITLE
Unable to DL pages or use web-view

### ISSUE THREAD

**Issue by BiddinWar** [keiyoushi/extensions-source#2327]
### Source information

The Blank Scanlation 1.4.35

### Source language

English

### Steps to reproduce

1. Download repo for "The Blank Scanlation"
2. Install said repo
3. Browse extension/repo for manga "A Sweet Part Time Job" (Used for example)
4. Attempt to download latest chapter
5. Observe inability due to "No pages found" error message
6. Attempt to use "webview"
7. Observe website loads for a moment, then loads again and presents "What are you looking for from <theblank.net>?"
8. Observe URL at the top being `theajack.github.io/disable-devtool/404.html?h=theblank.net`

### Expected behavior

Able to DL latest chapters/pages
Able to view website with webview

### Actual behavior

Unable to DL chapters/pages
Unable to view website with Webview

### Mihon/Tachiyomi version

Stable 0.16.4

### Android version

Android 14

### Other details

Appears that TheBlank.net is using https://theajack.github.io/disable-devtool/ to disable the webview, which maybe has an effect on being unable to find pages either for DL on newer chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems like part of #2315

Using your example, I am able to view chapters other than 30 & 31 (since they are locked behind the source's paywall)

Try checking other chapters

**Comment by BiddinWar** [comment]
I see 🤔 29 28 and older was fine, only noticed it with 30/31 but didn't realise its part of their paywall. Is there a way around this issue for me or do I just ignore them for now until whenever they're out of paywall?

**Comment by Norsze** [comment]
There's a fix coming, that will exclude those chapters from showing, so just ignore the paid stuff until it is free
