### ISSUE TITLE
Drake Scans titles show chapters in reverse order

### ISSUE THREAD

**Issue by SadderWhale** [keiyoushi/extensions-source#2446]
### Source information

Drake Scans 1.4.40

### Source language

English

### Steps to reproduce

1. Open Drake Scans
2. Open a title

### Expected behavior

Chapters should go latest to oldest as you scroll down

### Actual behavior

Chapters go oldest to latest as you scroll down

### Mihon/Tachiyomi version

Preview r556

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #2395, read the comments in there, not an extension issue.

Also search the issues before making a new one & acknowledging that you did

**Comment by Norsze** [comment]
from what I can see this issue is resolved now. Might be some weirdness still going on with them seemingly uploading a lot of chapters the same day, but most of the sorts seem to be correct now and on their side
