### ISSUE TITLE
Problème source

### ISSUE THREAD

**Issue by kirito58** [keiyoushi/extensions-source#2559]
### Source name

Tout les source

### Source link

Tout

### Source language

Arabe

### Other details

Help
![Screenshot_2024-04-24-21-55-45-774_app mihon](https://github.com/keiyoushi/extensions-source/assets/146889079/dcd4a152-2f97-485d-a6d4-2fc69429265b)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Literally no info in this report

**Comment by Norsze** [comment]
If this is a source request type the URL for the source under "source link"

**Comment by Norsze** [comment]
Ok, just no, everything they did was wrong and I will close this:

1. Didn't use English
2. Bad title
3. Bad description
4. Didn't open the right type of issue
5. It's a network issue on their end, they messed something up
