### ISSUE TITLE
Manhwa Freak down

### ISSUE THREAD

**Issue by FaTe-code** [keiyoushi/extensions-source#2678]
### Source information

Manhwa Freak 1.4.35

### Source language

English 

### Steps to reproduce

Open either manhwa freak source or a chapter from source manhwa.
Webview works.

### Expected behavior

Showing all the manhwa when source itself is opened and chapters loading.

### Actual behavior

Source page not found and chapter pages not found.

### Mihon/Tachiyomi version

Tachiyomi J2K 1.7.4

### Android version

Android 10

### Other details

![Screenshot_20240430-024013_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/65074719/8f2a7ba4-6f3b-4fcf-b934-afefc2a96041)
![Screenshot_20240430-024113_TachiyomiJ2K](https://github.com/keiyoushi/extensions-source/assets/65074719/e805f5ce-ff74-45c1-8e91-f1eca52d81a5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by FaTe-code** [comment]
Duplicate

**Comment by Norsze** [comment]
#2677
