### ISSUE TITLE
Hoi Fansub HTTP 404

### ISSUE THREAD

**Issue by ghost** [keiyoushi/extensions-source#2872]
### Source information

Hoi Fansub 1.4.36

### Source language

Turkish

### Steps to reproduce

Open Hoi fansub

### Expected behavior

The source has to work.

### Actual behavior

But the source does not work. It only works in WebView.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
What manga did you manage to read in WebView? All the ones I tested shows a 404 error.

**Comment by ghost** [comment]
The issues with the Hoi fansub source has been fixed.
