### ISSUE TITLE
Sarcasm Scans HTTP 404

### ISSUE THREAD

**Issue by ghost** [keiyoushi/extensions-source#2873]
### Source information

Sarcasm Scans 1.4.36

### Source language

Turkish

### Steps to reproduce

Open Sarcasm Scans

### Expected behavior

The source has to work.

### Actual behavior

But the source does not work. It only works in WebView.

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Same as with #2872, I only get a 404 error whenever I try to open any manga from the WebView. Which one works for you?

**Comment by ghost** [comment]
> Same as with #2872, I only get a 404 error whenever I try to open any manga from the WebView. Which one works for you?

For me both sources work fine in WebView. But in the app it gives HTTP 404 error.

**Comment by vetleledaal** [comment]
What manga are you testing with specifically? This is what I get: 
![image](https://github.com/keiyoushi/extensions-source/assets/13540478/40b61005-aef2-4403-a467-bb8f2f8759d7)

**Comment by ghost** [comment]
When I checked the manga again, it started giving me the same warning it gave you. I think there is a problem with the source itself.

**Comment by ghost** [comment]
The issues with the Sarcasm Scans source has been fixed.
