### ISSUE TITLE
MangaGeko

### ISSUE THREAD

**Issue by uniqueunique7x7** [keiyoushi/extensions-source#3008]
### Source information

MangaGeko 1.4.21

### Source language

English

### Steps to reproduce

![Screenshot_20240513-220917_Mihon](https://github.com/keiyoushi/extensions-source/assets/117525478/c4667cdd-1f35-454b-aed4-230c2549c20f)
![Screenshot_20240513-221002_Mihon](https://github.com/keiyoushi/extensions-source/assets/117525478/322db4ce-f109-450b-9bee-fda61e560592)

### Expected behavior

Page should load but it won't.

### Actual behavior

Page not found in mihon but workin in browser.

### Mihon/Tachiyomi version

1.4.21

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #3000

**Comment by NidPlays** [comment]
Seems to be working now

Edit: getting HTTP 500 internal server error
