### ISSUE TITLE
Open source links directly in-app

### ISSUE THREAD

**Issue by Hash6232** [keiyoushi/extensions-source#3279]
### Source name

MangaDex

### Source language

English

### Describe your suggested feature

Back when Tachi was still maintained, I could open mangadex links directly in-app. Now, by default, they are opened in the browser. I am not sure if this is supposed to be an extension or main-app feature.

### Other details

- Mihon Stable 0.16.5
- Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AwkwardPeak7** [comment]
It still exists, you just need to manually verify links in android settings.

browse > extensions > MangaDex > app settings > open supported links (or similar depending on your phone)

you can come to our discord for further help
