### ISSUE TITLE
HentaiNexus en.hentainexus 1.4.9 chapter error

### ISSUE THREAD

**Issue by kevin01523** [keiyoushi/extensions-source#3508]
### Source information

HentaiNexus en.hentainexus 1.4.9

### Source language

english

### Steps to reproduce

install extention
click browse 
manga lists appear
click one manga
click one chapter
shows  chapter error with corrupted text

### Expected behavior

install extention
click browse 
manga lists appear
click one manga
click one chapter
able to view chapter image

### Actual behavior

install extention
click browse 
manga lists appear
click one manga
click one chapter
shows  chapter error with corrupted text

### Mihon/Tachiyomi version

tachiyomisy 1.10.5

### Android version

android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Maybe related/fixed by #3502

**Comment by kevin01523** [comment]
> Maybe related/fixed by #3502

yeah i did expect it was xor since only xor would produce corrupted characters on plain text
