### ISSUE TITLE
Fecomic source request

### ISSUE THREAD

**Issue by Karutovn** [keiyoushi/extensions-source#3572]
### Source name

Fecomic

### Source link

https://fecomicc.xyz/

### Source language

Vietnamese 

### Other details

18+/nsfw = true

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Is the site working for you? I have been checking in periodically for the past 2 weeks, but none of the pages load.

**Comment by Karutovn** [comment]
When i request this source (it's work) but now i can't read it

**Comment by Karutovn** [comment]
I think i need to close this source as not planned (I don't have the respond from website admin and i don't see the translation team to talking about that)
