### ISSUE TITLE
Lavinia Fansub: SSLHandshakeException / CertPathValidatorException on browse

### ISSUE THREAD

**Issue by ghost** [keiyoushi/extensions-source#3786]
### Source information

Lavinia Fansub 1.4.36

### Source language

Turkish 

### Steps to reproduce

Go Lavinia Fansub

### Expected behavior

The source must work.

### Actual behavior

But the source doesn't work in the app and it says; 

SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Source only work in WebView. 

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to load up the extension's browse page fine after checking WebView & clicking around. If it still appears, follow this troubleshooting guide - https://mihon.app/docs/guides/troubleshooting/common-issues#java-security-cert-certpathvalidatorexception-chain-validation-failed

Also, it seems like they are experiencing some issues, maybe it's still ongoing (see attached picture) & could be the cause of said issue: 
![Screenshot 2024-06-27 131332](https://github.com/keiyoushi/extensions-source/assets/155411819/a01f19cc-3c8c-48ef-b3dd-eccea7df79fd)

**Comment by AwkwardPeak7** [comment]
certificate issue is no more, tho chapter names are not showing, you can open a new issue for that
