### ISSUE TITLE
Junmeitu: No chapters found

### ISSUE THREAD

**Issue by 0Ha16wA5** [keiyoushi/extensions-source#392]
### Source information

Junmeitu 1.4.6

### Source language

All

### Steps to reproduce

1. Choose Browse > Sources > Junmeitu
2. Choose any entry
3. Error message "No chapters found" appeared
I tried to check via webview, and all of them accessible in webview
![Screenshot_2024-01-20-01-21-09-943_xyz jmir tachiyomi mi debug](https://github.com/keiyoushi/extensions-source/assets/138314566/f6dbf41d-6667-4127-bff1-9daf2e5c2137)

### Expected behavior

Entry appeared as chapter.

### Actual behavior

"No chapters found" error message.

### Tachiyomi version

Aniyomi Preview r7473 and TachiyomiSY Preview r542

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by SnakeDoc83** [comment]
Can't reproduce in either app. Make sure you've got the updated extension trusted in both your apps, clear cache & database, and try again. Also try refreshing that particular entry.

**Comment by 0Ha16wA5** [comment]
@SnakeDoc83 I did all of that.
I tried the extension on fresh installed Mihon, and it works flawlessly.

It seems the only fix is resetting the entire app.

Probably corrupted files problem?

**Comment by SnakeDoc83** [comment]
> Probably corrupted files problem?

Maybe, definitely some kind of weirdness.
