### ISSUE TITLE
ColoredManga Broken❗❗

### ISSUE THREAD

**Issue by Bipolar708** [keiyoushi/extensions-source#3955]
### Source information

Coloredmanga 1.4.37

### Source language

English

### Steps to reproduce

Download and open extension...... it says no results found

### Expected behavior

Show manga titles

### Actual behavior

Displays no results found

### Mihon/Tachiyomi version

Aniyomi preview r7714

### Android version

Android 14

### Other details

The site was down for a while it recently came back but seems to have some problems

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by qorrymarzuki** [comment]
Yes it's broken. The coloredmanga site admin said they use generative image. I don't really understand what it means, but he's saying it will be hard to make coloredmanga as tachiyomi extension.

**Comment by AwkwardPeak7** [comment]
Extension works, you are not using our repo version
