### ISSUE TITLE
I want to request the addition of a new extension that appeared in Portuguese Brazil 

### ISSUE THREAD

**Issue by Astatrevo** [keiyoushi/extensions-source#4215]
### Source name

Central novel

### Source link

https://centralnovel.com/

### Source language

Português Brasil - PT BR

### Other details

![Screenshot_20240724-113416](https://github.com/user-attachments/assets/934e9be5-bab7-4541-a7ff-d0411c86d49f)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by choppeh** [comment]
:pushpin: #4027 (Novels again)
