### ISSUE TITLE
Scan Manga Fr base url change

### ISSUE THREAD

**Issue by yohanim** [keiyoushi/extensions-source#4754]
### Source information

Extension name: Scan-Manga (lang: fr; package: eu.kanade.tachiyomi.extension.fr.scanmanga) Extension version: 1.4.7

### Source language

French

### Source new URL

https://www.scan-manga.com

### Other details

Maybe other parts like pages are also changed.
Right now no search work and all screens end up with error 500
Search does not work(new full url of series titles https://www.scan-manga.com/scanlation/liste_series.html)
Top does not work(new full url https://www.scan-manga.com/TOP-Manga-Webtoon-27.html)
Latest does not work(new full url https://www.scan-manga.com/?po)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KirinRaikage** [comment]
Duplicate of #2232
