### ISSUE TITLE
Radiant Scans Shut Down

### ISSUE THREAD

**Issue by JIINNN01** [keiyoushi/extensions-source#5645]
### Source name

Radiant Scans

### Source language

English

### Source link

https://radiantscans.com/

### Other details

They have shutdown. The group merged with Realm Scans(Rizz Comic)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Mmoryhunter** [comment]
Rizz comics is the same as Rizzfables, right?

**Comment by JIINNN01** [comment]
Yep
