### ISSUE TITLE
Es.Mi2Manga Global And Individual Search Error

### ISSUE THREAD

**Issue by Padahjj** [keiyoushi/extensions-source#5942]
### Source information

Es.Mi2Manga 1.4.37

### Source language

Spanish

### Steps to reproduce

1. Open the extension 
2. Search for a work that is on the site
3. Or search for the work in the global search tab 

### Expected behavior

The work should appear after searching for

### Actual behavior

HTTP error 040 appears

![20241107_195938924](https://github.com/user-attachments/assets/6dde460e-24ef-4bb8-b53b-37611dd02591)

### Mihon/Tachiyomi version

TachiyomiSY 1.11.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Seems like it was a URL change that the site reverted, it's working fine now
