### ISSUE TITLE
Rawkuma connection issue

### ISSUE THREAD

**Issue by RadStorm04** [keiyoushi/extensions-source#617]
### Source information

Rawkuma 1.4.28

### Source language

Japanese

### Steps to reproduce

1.Click on source 2.Unable to access content list (http 500)
![Screenshot_20240125_204058_Mihon](https://github.com/keiyoushi/extensions-source/assets/2616683/3967e574-aea7-4485-add2-362bda6089e9)

### Expected behavior

Access content list normally

### Actual behavior

Won't load (http 500)

### Tachiyomi version

Mihon 1.16.1

### Android version

Android 14

### Other details

Books that are already in library are still viewable

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by l2eused** [comment]
Is that work now? this not happen for me. maybe error500 is server issue not by extension

**Comment by RadStorm04** [comment]
It fixed itself, turns out it's just me being too sensitive...😅
