### ISSUE TITLE
Happymh could not pass cloudflare

### ISSUE THREAD

**Issue by Wistar1308** [keiyoushi/extensions-source#6273]
### Source information

Happymh 1.4.13

### Source language

Chinese

### Steps to reproduce

1. choose webview 
2. Pass webview cloudflare test
3. Back to chapter
4. Choose chapter 
5. Back screen and keep loading 
6. Show could not pass cloudflare message 

### Expected behavior

Should show galleries 

### Actual behavior

Back screen and keep loading 

### Mihon/Tachiyomi version

0.15.3

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by raine93** [comment]
Unfortunately,  any cloudflare issues they will just close the issues

**Comment by Rstoroniomi** [comment]
yes，I cannot use it ，either

**Comment by BabyNurse020517** [comment]
still facing this
