### ISSUE TITLE
An extension is not working

### ISSUE THREAD

**Issue by Willian00175** [keiyoushi/extensions-source#6315]
### Source information

SlimeRead 1.4.14

### Source language

Brazilian Portuguese

### Steps to reproduce

First step: go to strong second step select the extension or go to the webview

### Expected behavior

Being able to access the webview or the works

### Actual behavior

![Screenshot_20241126-094339](https://github.com/user-attachments/assets/8095d647-1aa9-4653-b842-3e740f6353cb)
![Screenshot_20241126-094417](https://github.com/user-attachments/assets/16610e9e-1631-4374-8bc3-f02fb27c149f)

### Mihon/Tachiyomi version

App version: 0.17.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
You made a duplicate issue #6242 Shame on you, can't you read?
