### ISSUE TITLE
Manga Ship not working

### ISSUE THREAD

**Issue by ReCoffee** [keiyoushi/extensions-source#6368]
### Source information

Manga Ship 1.4.3

### Source language

Turkish

### Steps to reproduce

1 I opened the repo and came across these 
![image](https://github.com/user-attachments/assets/f1e07aff-7e3c-4a91-83c8-09a38e512647)

2 I thought it might be a mistake, so I went to the web to see if it could be fixed. 
![image](https://github.com/user-attachments/assets/8e90ec17-1215-4697-a4cf-d0d29d35bf81)

3 but nothing changed 
![image](https://github.com/user-attachments/assets/f025855c-ef9e-48ea-82c1-7254e178db03)
![image](https://github.com/user-attachments/assets/bc5c89c2-1dc8-4c9f-980c-3d55b126b448)

### Expected behavior

Series nothing works

### Actual behavior

This time the site is working properly, but there seems to be an error in the repo. I thought it would be fixed by accessing the web and it didn't work. I cleared cookies etc. It didn't work. It shows only one series and there is nothing in that episode.

### Mihon/Tachiyomi version

Mihon 1.17.7015 (Beta)

### Android version

Android 13

### Other details

I guess I don't have any more details to give, I can write them if you want, thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by dngonz** [comment]
Duplicate #1100
