### ISSUE TITLE
Novo link da sussy

### ISSUE THREAD

**Issue by Jefferson199809** [keiyoushi/extensions-source#6434]
### Source information

Sussy scan

### Source language

Português-br

### Steps to reproduce

O link da sussy 
Passou de :https://oldi.sussytoons.com/
Para:https://new.sussytoons.site/

### Expected behavior

Obras atualizadas

### Actual behavior

As obras não estão se atualizando pq o site atual vai ser descontinuado e vai ser o do novo link

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 11

### Other details

As obras não estão se atualizando 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
Duplicate of #6034
