### ISSUE TITLE
Improve hiding NSFW (Browse setting)

### ISSUE THREAD

**Issue by CrimsonBloodfang** [keiyoushi/extensions-source#6481]
### Source name

Comick

### Source language

English

### Describe your suggested feature

Advance mode that blocks or hides extensions or sources with the word or tag hentai/erotic/nsfw and can whitelist specific extensions. I mainly use Comick and it gets removed when I enable the option in Settings>Browse>NSFW. Need some kind of versatility with this setting.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
This request is more related to the app than to the extensions. The extensions just have a tag if they have NSFW or not. So maybe put a request in the GitHub for the app you use about a whitelist for installed sources.
