### ISSUE TITLE
image decoding crash

### ISSUE THREAD

**Issue by mm12** [keiyoushi/extensions-source#6541]
### Source information

MangaDex 1.4.195

### Source language

English

### Steps to reproduce

1. Download Chapter
2. Open Chapter

### Expected behavior

Chapter Loads

### Actual behavior

1. Chapter load spinner starts
2. Entire app crashes (No crash "catch" screen), exits to home screen
3. The residual 'reading mode' toast (eg, left to right) appears

NOTE: Sometimes, it fails back to the entry instead of out of the app. I will investigate further. Both crash logs are now included.

### Mihon/Tachiyomi version

0.17.1

### Android version

Android 15

### Other details

Full crash:
[mihon_crash_logs.txt](https://github.com/user-attachments/files/18056289/mihon_crash_logs.txt)
Entry failback:
[mihon_crash_logs_menu.txt](https://gi
thub.com/user-attachments/files/18056330/mihon_crash_logs_menu.txt)

Imported from mihonapp mihon # 1555 

Based on the changes to the extension, the update will not fix it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
:)

How about with 1.4.196? (Don't think it has any changes related to said issue, but just in case)

**Comment by mm12** [comment]
Just tested, same behavior. This time I didn't have it downloaded, though, so that isn't a required step.

**Comment by Smol-Ame** [comment]
You mentioned in the linked issue that it happens with a particular entry/chapter, what's the entry/chapter?

**Comment by Smol-Ame** [comment]
You mentioned in the linked issue that it happens with a particular entry/chapter, what's the entry/chapter?

**Comment by mm12** [comment]
https://mangadex.org/chapter/927ad6bd-bf87-4c48-bccf-140338f44883

**Comment by Norsze** [comment]
You shouldn't link to Mihon from this repo or any other repo to be honest, unless you want it to be easily linked to a bunch of apps and then have Github purge everything. For that you are kinda dumb.

Next I looked at the log and you are trying to access a corrupt page/URL that can't be displayed on even a browser.

![image](https://github.com/user-attachments/assets/9721595b-5fd1-492f-8179-c953595aac40)

**Comment by mm12** [comment]
> You shouldn't link to Mihon from this repo or any other repo to be honest, unless you want it to be easily linked to a bunch of apps and then have Github purge everything. For that you are kinda dumb.

Rude. I have seen it here before and therefore thought it was fine. 

> Next I looked at the log and you are trying to access a corrupt page/URL that can't be displayed on even a browser.

It displays in webview fine.

**Comment by mm12** [comment]
![image](https://github.com/user-attachments/assets/79fec39c-9155-4e76-bc2e-ca464ef20eb3)

**Comment by Norsze** [comment]
It's your phone that is trying to access the corrupt link, not mine, works fine for me, so it's you issue. Figure it out.

**Comment by AwkwardPeak7** [comment]
> You shouldn't link to Mihon from this repo or any other repo to be honest, unless you want it to be easily linked to a bunch of apps and then have Github purge everything. For that you are kinda dumb.

Honestly doesn't matter...

**Comment by Norsze** [comment]
Doesn't matter either way cause it is isolated to his phone

**Comment by AwkwardPeak7** [comment]
The crash log says it is failing on image decoder so try to clear chapter cache and try again otherwise go bug mihon people

**Comment by mm12** [comment]
> It's your phone that is trying to access the corrupt link, not mine, works fine for me, so it's you issue. Figure it out.

the image you are referring to is MD @ HOME: https://github.com/keiyoushi/extensions-source/blob/main/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MdAtHomeReportInterceptor.kt#L39 

> Doesn't matter either way cause it is isolated to his phone

Opened on my laptop fine too.

**Comment by mm12** [comment]
> The crash log says it is failing on image decoder so try to clear chapter cache and try again otherwise go bug mihon people

Thanks, will bug them

**Comment by mm12** [comment]
Anyway, if you wanna nuke this to fix it, please do. Deleting the issue will remove the cross ref.

> You shouldn't link to Mihon from this repo
