### ISSUE TITLE
Bump issue template

### ISSUE THREAD

**Issue by mm12** [keiyoushi/extensions-source#6542]
### Describe why this should be added

Issue template is outdated. Current app version is 0.17.1. Perhaps add a chore to pull the latest version number?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/mihonapp/mihon/issues/new/choose).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Smol-Ame** [comment]
It hasn't been changed since it's still compatible with dead Tachi 0.15.3 (which some people still use)

**Comment by mm12** [comment]
maybe "or higher"

**Comment by Norsze** [comment]
It is an example, just like "Android 11" is just an example. Doesn't need to be the newest in this case, if it was a reader app development, then yes, but the repo is not bound to any specific app. If anything we should update it to say to include the app name
