### ISSUE TITLE
Happymh can't identify chapter correctly

### ISSUE THREAD

**Issue by NeKoOuO** [keiyoushi/extensions-source#6697]
### Source information

Happymh 1.4.15

### Source language

Chinese

### Steps to reproduce

https://github.com/user-attachments/assets/54c8f5a4-dae0-4096-b74a-88b595bedb0d

### Expected behavior

Chapters should be correctly identified, just like secondary sources

### Actual behavior

It's all Ch.0

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Norsze** [comment]
This is a parsing issue, nothing more. It is also very low priority as the display as source works as intended and shows the exact name that the website shows

**Comment by NeKoOuO** [comment]
No, I don't think so, because when I'm using it, the chapter sync always misidentifies all chapters as chapter 0, so it marks them as read even though I haven't read that chapter.

**Comment by Norsze** [comment]
The contributor literally said the url changes, he knows more than you

**Comment by Norsze** [comment]
And if they are related then you are just an idiot who opened a duplicate issue

**Comment by NeKoOuO** [comment]
Personal attacks will not make what you're saying seem more reasonable.

**Comment by Norsze** [comment]
ok, so idiot
