### ISSUE TITLE
new extensions request

### ISSUE THREAD

**Issue by SupKelelawar** [keiyoushi/extensions-source#750]
### Source name

sektelomik.xyz, neumanga.xyz, komikzoid.id

### Source link

https://sektekomik.xyz, https://neumanga.xyz, https://komikzoid.id

### Source language

Indonesia

### Other details

this is different website, sektekomik and neumanga not using mangathemesia theme

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by beerpiss** [comment]
Please make one issue for each website. And also, read the acknowledgements.

**Comment by SupKelelawar** [comment]
> ### Source name
> sektelomik.xyz, neumanga.xyz, komikzoid.id
> 
> ### Source link
> https://sektekomik.xyz, https://neumanga.xyz, https://komikzoid.id
> 
> ### Source language
> Indonesia
> 
> ### Other details
> this is different website, sektekomik and neumanga not using mangathemesia theme
> 
> ### Acknowledgements
> * [x]  I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/keiyoushi/extensions-source/) and verified it does not appear in the code base.
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
> * [x]  I have written a meaningful title with the source name.
> * [x]  I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
> * [x]  I will fill out all of the requested information in this form.
