### ISSUE TITLE
Source request of Boxmanhwa

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/extensions-source#922]
### Source name

Boxmanhwa

### Source link

https://boxmanhwa.com/

### Source language

English

### Other details

18+/NFSW+
![Screenshot_2024-02-02-18-40-54-986_com android chrome](https://github.com/keiyoushi/extensions-source/assets/145904014/e9431acb-6488-4f68-a792-df5a9a6d8c30)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by devil6venom** [comment]
Uses madtheme!
