### ISSUE TITLE
Extensions for Paid Platforms offering DRM Free downloads of paid content

### ISSUE THREAD

**Issue by Neshura87** [keiyoushi/extensions-source#94]
### Describe why this should be added

iirc Tachiyomi itself always had a strict policy disallowing Extensions for platforms where users buy content and then have the ability to download it without DRM. Will you also implement this policy or would it be fine to add extensions like that to the repo? (totally fine if not but given that this is quickly becoming the new default repo it would give more people access to such extensions)

to clarify:
1: Extensions would not break DRM
2: Extensions would not pirate content from those sites (same as 1 imo)
3: Users would be required to provide login credentials in the settings (not sure if this is safe, it might be a blocker)
4: Users would only have access to content they can already download if they visited the Site the Extension is for (same as 1 and 2 imo)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.15.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabriel062323** [comment]
i will waiting for this

**Comment by FengTeLai** [comment]
我也想知道这个提议能否被的接受。
在部分平台购买作品，一段时间后作品即将下架或已下架，用户无法再阅读章节，是否可以通过拓展完成章节下载？

**Comment by FourTOne5** [comment]
I will allow it as long it uses public api and not api reverse engineered from their app
